--- #YAML:1.0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.11
license: perl
name: Thesaurus
recommends:
  BerkeleyDB: 0.19
  Text::CSV_XS: 0
requires:
  Params::Validate: 0.24
version: 0.20
